version: '3'
services:
  bot:
    container_name: botPromo
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TOKEN=<your_token_here>
      - SEMESTER=<your_semester_here (odd or even)>
